"""Reorder-mode agent loop (PRD Section 2, Section 6). Allocation mode is
added in Day 13.

Standard Claude tool-use loop: send messages + tool schemas, execute
whichever tool Claude calls against the real DB, feed the result back,
repeat until Claude stops calling tools. No number in the final
recommendation is generated by the LLM -- every numeric field traces back
to a tool call in src/agent/tools.py.
"""

import json

import anthropic
from dotenv import load_dotenv

from src.agent.tools import TOOL_FUNCTIONS, TOOL_SCHEMAS

load_dotenv()

MODEL = "claude-sonnet-5"
MAX_TOOL_ITERATIONS = 8

REORDER_TOOL_NAMES = {
    "get_stock_position",
    "get_project_schedule",
    "get_supplier_options",
    "compute_reorder_point",
    "draft_purchase_order",
}

REORDER_SYSTEM_PROMPT = """You are a Solar EPC inventory reorder assistant.

You never invent a number. Reorder point, EOQ, and stock levels always come
from tool calls -- your job is to read the unstructured context tools give
you (supplier notes, project schedule) and reason about what a formula alone
can't see: for example, two suppliers tied on lead time and price, but one
with a history of late shipments.

Investigate the item using the available tools, then, if a reorder is
justified, call draft_purchase_order with your chosen supplier, quantity,
and a concise written rationale. If no reorder is justified, say so in your
final response and do not call draft_purchase_order."""


def _tool_schemas_for(names: set) -> list:
    return [schema for schema in TOOL_SCHEMAS if schema["name"] in names]


def _execute_tool(conn, name: str, tool_input: dict) -> dict:
    function = TOOL_FUNCTIONS[name]
    try:
        return function(conn, **tool_input)
    except ValueError as e:
        return {"error": str(e)}


def run_reorder_agent(conn, item_id: str, model: str = MODEL) -> dict:
    client = anthropic.Anthropic()
    tools = _tool_schemas_for(REORDER_TOOL_NAMES)

    messages = [
        {
            "role": "user",
            "content": (
                f"Item {item_id} may need reordering soon. Investigate stock "
                f"position, project schedule, and supplier options, then "
                f"decide whether to draft a purchase order."
            ),
        }
    ]

    drafted = None
    for _ in range(MAX_TOOL_ITERATIONS):
        response = client.messages.create(
            model=model,
            max_tokens=1500,
            system=REORDER_SYSTEM_PROMPT,
            tools=tools,
            messages=messages,
        )
        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason != "tool_use":
            final_text = "".join(block.text for block in response.content if block.type == "text")
            return {"drafted": drafted, "final_text": final_text}

        tool_results = []
        for block in response.content:
            if block.type != "tool_use":
                continue
            result = _execute_tool(conn, block.name, block.input)
            if block.name == "draft_purchase_order" and "error" not in result:
                drafted = result
            tool_results.append({"type": "tool_result", "tool_use_id": block.id, "content": json.dumps(result)})
        messages.append({"role": "user", "content": tool_results})

    return {"drafted": drafted, "final_text": "(stopped: max tool iterations reached without a final response)"}
