"""Reorder-mode and allocation-mode agent loops (PRD Section 2, Section 6).

Both are the same underlying Claude tool-use loop: send messages + tool
schemas, execute whichever tool Claude calls against the real DB, feed the
result back, repeat until Claude stops calling tools. No number in the
final recommendation is generated by the LLM -- every numeric field traces
back to a tool call in src/agent/tools.py. The two entry points
(run_reorder_agent, run_allocation_agent) differ only in which tools are
exposed, the system prompt, and the initial message.
"""

import json

import anthropic
from dotenv import load_dotenv

from src.agent.tools import TOOL_FUNCTIONS, TOOL_SCHEMAS

load_dotenv()

MODEL = "claude-sonnet-5"
MAX_TOOL_ITERATIONS = 8

REORDER_TOOL_NAMES = {
    "get_stock_position",
    "get_project_schedule",
    "get_supplier_options",
    "compute_reorder_point",
    "draft_purchase_order",
}

REORDER_SYSTEM_PROMPT = """You are a Solar EPC inventory reorder assistant.

You never invent a number. Reorder point, EOQ, and stock levels always come
from tool calls -- your job is to read the unstructured context tools give
you (supplier notes, project schedule) and reason about what a formula alone
can't see: for example, two suppliers tied on lead time and price, but one
with a history of late shipments.

Investigate the item using the available tools, then, if a reorder is
justified, call draft_purchase_order with your chosen supplier, quantity,
and a concise written rationale. If no reorder is justified, say so in your
final response and do not call draft_purchase_order."""

ALLOCATION_TOOL_NAMES = {
    "get_stock_position",
    "get_project_schedule",
    "get_contract_context",
    "compute_priority_scores",
    "draft_allocation_plan",
}

ALLOCATION_SYSTEM_PROMPT = """You are a Solar EPC inventory allocation assistant.

You never invent a number. The priority score for each competing project's
reservation always comes from a tool call -- your job is to read the
unstructured context tools give you (contract notes) and reason about what
a formula alone can't see: for example, two projects tied on priority score,
but one has a force-majeure clause capping its penalty exposure for
supplier-caused delay, which should lower its urgency relative to a project
without that protection.

Investigate the competing projects using the available tools, then call
draft_allocation_plan with your recommended allocation (a mapping of
project_id to allocated quantity) and a concise written rationale --
especially where your allocation differs from what the raw priority score
alone would produce."""


def _tool_schemas_for(names: set) -> list:
    return [schema for schema in TOOL_SCHEMAS if schema["name"] in names]


def _execute_tool(conn, name: str, tool_input: dict) -> dict:
    function = TOOL_FUNCTIONS[name]
    try:
        return function(conn, **tool_input)
    except ValueError as e:
        return {"error": str(e)}


def _run_tool_loop(
    conn,
    model: str,
    system_prompt: str,
    tool_names: set,
    initial_message: str,
    draft_tool_name: str,
) -> dict:
    client = anthropic.Anthropic()
    tools = _tool_schemas_for(tool_names)
    messages = [{"role": "user", "content": initial_message}]

    drafted = None
    for _ in range(MAX_TOOL_ITERATIONS):
        response = client.messages.create(
            model=model,
            max_tokens=1500,
            system=system_prompt,
            tools=tools,
            messages=messages,
        )
        messages.append({"role": "assistant", "content": response.content})

        if response.stop_reason != "tool_use":
            final_text = "".join(block.text for block in response.content if block.type == "text")
            return {"drafted": drafted, "final_text": final_text}

        tool_results = []
        for block in response.content:
            if block.type != "tool_use":
                continue
            result = _execute_tool(conn, block.name, block.input)
            if block.name == draft_tool_name and "error" not in result:
                drafted = result
            tool_results.append({"type": "tool_result", "tool_use_id": block.id, "content": json.dumps(result)})
        messages.append({"role": "user", "content": tool_results})

    return {"drafted": drafted, "final_text": "(stopped: max tool iterations reached without a final response)"}


def run_reorder_agent(conn, item_id: str, model: str = MODEL) -> dict:
    return _run_tool_loop(
        conn,
        model=model,
        system_prompt=REORDER_SYSTEM_PROMPT,
        tool_names=REORDER_TOOL_NAMES,
        initial_message=(
            f"Item {item_id} may need reordering soon. Investigate stock "
            f"position, project schedule, and supplier options, then "
            f"decide whether to draft a purchase order."
        ),
        draft_tool_name="draft_purchase_order",
    )


def run_allocation_agent(conn, project_ids: list, item_id: str, model: str = MODEL) -> dict:
    return _run_tool_loop(
        conn,
        model=model,
        system_prompt=ALLOCATION_SYSTEM_PROMPT,
        tool_names=ALLOCATION_TOOL_NAMES,
        initial_message=(
            f"Projects {', '.join(project_ids)} are competing for a shared batch of "
            f"item {item_id}. Investigate stock, priority scores, and contract context "
            f"for each project, then decide how to allocate the available stock."
        ),
        draft_tool_name="draft_allocation_plan",
    )
